on: 
  push:
    branches: [main]
    paths: ['web/**']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy Config
        run: cp config.json web/config_link.json
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lhrnet # e.g. 'my-project'
          directory: web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}